### PR TITLE
Flip sign of phase shifter angles on Polish systems

### PR DESCRIPTION
**Pull request by rdzman**
- Thanks to Dr. Artjoms Obusevs for reporting.
- It appears that the voltages in the case file correspond pretty closely to a power flow solution in which the generator voltage setpoints are set equal to the corresponding bus voltages and the phase shifter angles have the opposite sign.
- The sign convention on phase shifters was changed shortly before the inclusion of the original Polish cases, and probably after they were created. This change was made to match the convention used by PSS/E, PowerWorld, PSAT, etc.

### CODE REVIEW

**Comment by rdzman** [comment]
I've attached a script `test_polish_case_phase_shifters` that demonstrates the issue. On my system, with the original files (before the 8e22dd7 commit), it gives the following output.

```text
>> test_polish_case_phase_shifters


case2383wp
6 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:   2520.00    160.59
 PF soln:   2516.40    161.75  0.769351
w/rev PS:   2520.00    160.59  4.0232e-06


case2736sp
2 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:    740.00    -38.00
 PF soln:    738.32    -32.07  0.286268
w/rev PS:    740.00    -38.74  0.000338463


case2737sop
2 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:    390.15     11.00
 PF soln:    389.16     14.80  0.288869
w/rev PS:    390.15      9.75  0.000372201


case2746wop
1 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:    740.00     -6.91
 PF soln:    740.21     -8.25  0.0554534
w/rev PS:    740.00     -8.27  0.000252112


case2746wp
1 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:   1110.00    -30.00
 PF soln:   1110.65    -30.46  0.0568489
w/rev PS:   1110.00    -30.29  0.00023264


case3012wp
0 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:    740.00    149.34
 PF soln:    870.03    147.04  1.08168
w/rev PS:    870.03    147.04  1.08168


case3120sp
0 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:   1050.00    104.76
 PF soln:   1619.99    510.17  18.8896
w/rev PS:   1619.99    510.17  18.8896


case3375wp
2 phase shifters
 slack        Pg        Qg     |∆V| 
---------  --------  --------  -----
   input:    740.00    150.30
 PF soln:    738.56    150.59  0.458406
w/rev PS:    740.14    150.33  0.00137515
```

The question is which is correct in the original case files, the phase shifter data or the bus voltage solution data? Hopefully, the creator of the cases can help us out here.

**Comment by ccoffrin** [comment]
These cases, as they are currently, have been used in a wide variety of research studies.  I would take care before changing them at this point.  That said, these changes do appear to be fairly minor.

**Comment by rdzman** [comment]
Point well taken.

**Comment by rdzman** [comment]
Roman Korab, who created the cases, confirms that the phase shift angles were based on the old sign convention and so should have the opposite sign. Since the effect is small, I think I'll go ahead and make the change and just add an explicit note in the case files themselves.

**Comment by rdzman** [comment]
Any objections?

**Comment by ccoffrin** [comment]
fine by me.

**Comment by rdzman** [comment]
Force-pushed a re-based version in preparation for merging.

**Pull request merged**
