### PR TITLE
OPF variants

### PR DESCRIPTION
**Pull request by BaljaaSS**
Adds 3 new AC OPF variants, for a total of 4, including all combinations of:
- current and power representations of nodal balance equations
- polar and cartesian representation of bus voltage variables

Controlled by new MATPOWER options:
- `opf.current_balance` - 0 (default) for power balance, 1, for current balance
- `opf.v_cartesian` - 0 (default) for polar, 1 for Cartesian representation of voltages

### CODE REVIEW

**Comment by BaljaaSS** [comment]
First pull request

**Comment by rdzman** [comment]
In response to your e-mail:

- I suspect the Ipopt and Knitro tests are passing for you because you do not have either of those solvers installed (so it's actually skipping all of the tests). But these tests are essentially identical to the MIPS and fmincon tests. Let's focus on MIPS first, then we can update the rest, once we get all of the MIPS tests passing.

- MIPS tests are now running for me without fatal errors, but many are failing because of bus voltage magnitudes not being enforced. I assume you are also seeing these failures. In polar coordinates these limits are taken care of by bounds on the `Vm` variables directly. With cartesian coordinates, these limits will have to be added as additional nonlinear constraints (complete with the functions to evaluate the constraints and derivatives). It will also require extracting the appropriate shadow prices for `bus(:, MU_VMIN)` and `bus(:, MU_VMAX)`. These are currently being set based on shadow prices on the bounds on the real part of voltage, which is not correct.

- It seems that the general box limits on the `Vr` and `Vi` variables, specified in the call to `add_vars` should simply be `VMIN` and `VMAX`. This has been fixed in cc2575f.

- For reference buses, where voltage angles are fixed, we need an additional nonlinear equality constraint.

- I added `t_skip()` calls for the skipped tests, so that total number of tests is still correct.

- I also added two `error` calls to catch cases that are not implmented (branch angle difference limits and legacy OPF solvers that are hard coded to polar voltage representation).

- I'm guessing the fmincon error was related to setting voltage real and imaginary bounds based on voltage maginitude and angle bounds, the latter of which can be infinite. This error should be gone since I changed these bounds.

- Implementing the branch angle difference limit constraints (linear constraint `'ang'`) for cartesian coordinates will require yet another set of nonlinear constraints. It isn't just a simple linear constraint anymore. For the time being I have added an error message saying it is not yet implemented.

- Finally, when adding the variables, is there any reason to add the `Vi` variables before the `Vr` variables? The other order seems more intuitive and consistent to me (since that's how we handle `Pg`, `Qg`).

**Comment by BaljaaSS** [comment]
Sorry for late reply. I have been busy for a couple of days. I made a time that I can work on tests tomorrow. To get your changes on my local disk, should I do git pull or merge?

**Comment by rdzman** [comment]
You need to pull.

**Comment by BaljaaSS** [comment]
1. It is true that Ipopt and Knitro are not installed. I agree that let's focus on MIPS first.  

2.  A fmincon error is gone now. I saw other errors related to updating solution data in fmincopf_solver.m and running OPF with active power line limits in t_opf_fmincon.m. Errors are fixed by adding conditions for Cartesian coordinates. 

3. For adding the variables, there is no special reason to add the Vi before Vr. It was easier to remember that I can change Va by Vi and Vm by Vr than otherway around. 

4. I see that 178 tests are failed. If I understood correctly, we need to correct 3 things:
      4.1. Limits must be added as additional nonlinear constraints for cartesian. (I thought these limits are fixed in SHAcc2575f1ece4bb2ecf7dfbcbd293164530395fd1 or It is different thing)
      4.2. For reference buses, we also need an additional nonlinear equality
      4.3. Need to add nonlinear constraint 'ang' for cartesian coordinates. 
    However, it is not clear for me to how to correct them. For 4.1 and 4.2 can you please refer the line in the function or explain it more in details?  For 4.3, which difference limits do we want to compute? Real or Imaginary part of complex voltage? 

5.  When do you plan to release the next version of Matpower?

**Comment by rdzman** [comment]
3. Let's switch it to put the real part first, for consistency.

4.1 We are talking about two different sets of constraints. There are simple bounds on the optimization variables `Vr` and `Vi` which were being set incorrectly. These do not technically need bounds, but since these variables can never exceed the voltage magnitude, bounding them by -Vmax and Vmax restricts their range and could help convergence. (I see I made a mistake in using Vmin as the lower bound rather than -Vmax. This is fixed in 2000c83). The other set of constraints are those that actually restrict the magnitude of the complex voltage (i.e sqrt(Vr^2 + Vi^2) to lie between Vmin and Vmax. This is the nonlinear constraint that must be implemented and added to the formulation using `add_nln_constraint()`.

4.2 Correct.

4.3 For this you will have to add lines in `opf_setup()` with additional `add_nln_constraint()` calls that implement these constraints. For 4.3, it is the difference in voltage angle between the from and two bus of the corresponding branch. In cartesian coordinates it is no longer a simple linear constraint (difference between two optimization variables), rather it is a nonlinear function of 4 variables (real and imaginary part of voltage at each end). Let's focus on getting 4.1 and 4.2 done first. Once that's working we can add the `ang` constraint. I've added some commented lines to `opf_setup()` in 2000c83 to give you the idea of what I have in mind.

5. I've stopped trying to predict when I'll release new versions, but in the next few weeks I hope to get time to begin trying to finalize things for the next release.

**Comment by BaljaaSS** [comment]
3. I switched it to put the real part first in 7c64d3824c207d053a74dc1c2330cfc4197b76b6. However, I have some questions related to this. Does it mean that I have to change [Vi, Vr, Pg, Qg] = deal(x{:});  into [Vr, Vi, Pg, Qg] = deal(x{:}); as in line 43 in function **opf_power_balance_fcn** and other functions that are doing same? Also when I compute derivatives, I return the derivatives w.r.t Vi first than Vr in dg and d2G. Do we have to change the order as well?

4.1. I have created a function **opf_vlim_fcn** that returns derivatives of Vm w.r.t Vi and Vr. Do you want to compute dVm_dVr and dVm_dVi in a separate function that is maybe called dVm_dV or keep it like I did?  Same question for function **opf_vlim_hess** which I will make it later. Do you also want to include these derivatives in the Technical Note?

6. Are you going to edit TN2 or make new TN3 for all the new derivatives?

**Comment by rdzman** [comment]
3. Inside the constraint functions added via `add_nln_constraint` they appear in the order specified in the 6th argument of the corresponding call to `add_nln_constraint`. So for `opf_power_balance_fcn` it is determined by `nodal_balance_vars` defined (currently) in `opf_setup` line 274. So it should run without trouble as it is now, but for consistency, the order should be updated here too. In `t_opf_mips` line 142 it needs to be updated too, since this order here is directly determined by the order of the `add_var` calls.

4.1 Unless you are aware of another context in which it would be useful to have the separate function, I would say the way you have done it is fine for now. We can always refactor the code later to split that out into it's own function if it seems useful. Same for `opf_vlim_hess`. And yes, we should include these derivatives in the TN.

6. I haven't had time to think about this decision yet. For now, you can just add them to the supplement you wrote.

**Comment by BaljaaSS** [comment]
3. line 142 is updated in _t_opf_mips_.  Function **opf_vlim_hess** and **opf_vlim_fcn** are using the same order as it is given the 6th argument of the corresponding call to _add_nln_constraint_.  I think for **opf_power_balance_fcn** and **opf_power_balance_hess** we can do it later.

4.1 I have implemented the functions computing the derivatives and hessian of voltage magnitudes. I have questions about input arguments as you given as  (x, mpc, ref, mpopt) for **opf_vlim_fcn** and (x, lam, ref, mpopt). In **opf_vlim_fcn**, (mpc, ref, mpopt) are not used whereas (ref, mpopt) are not used in **opf_vlim_hess**. Maybe you can explain to me what are these inputs for. For lam in**opf_vlim_hess**, it is lamVm which is different than lamP and lamQ. Right?  Do we send lam= [lamP; lamQ; lamVm] or only lam=[lamVm]?

4.2 and 4.3 if you give me functions like you did for 4.1 (sqrt(Vr^2 + Vi^2)) then I can implement the functions (opf_vref_fcn, opf_vref_hess, opf_branch_ang_fcn, opf_branch_ang_hess) accordingly. Otherwise, it is still not clear to me what you are telling.

6. As I told you before, I am working on a comparison of these 4 variants. Now, I am going to write a paper about the comparison result. Due to the page limit, I cannot include all derivatives. Therefore, I will need to refer to somewhere for the derivatives of each variant. So I was thinking to refer to TN2 or new TN. It would be nice for me if you make the decision soon and tell me where I can refer to. Thank you.

**Comment by rdzman** [comment]
3. Ok, looks good. I went ahead and pushed a change that switches Vr and Vi for the following as well, so we should have a consistent order everywhere now:
    - `opf_power_balance_fcn`
    - `opf_power_balance_hess`
    - `opf_current_balance_fcn`
    - `opf_current_balance_hess`
    - `opf_branch_flow_fcn`
    - `opf_branch_flow_hess`
    - `nodal_balance_vars`
    - `flow_lim_vars`
    - `user_vars`

4.1 The `opf_vlim_fcn` needs to compute the nonlinear inequality constraint function for the lower and upper voltage limits, that is, the voltage magnitude _violations_, not just the voltage magnitude. In that sense, it is similar to `opf_branch_flow_fcn`, which computes flow limit _violations_ for "from" and "to" end of the branches, not just branch flows themselves. So we want something like

    Vm = sqrt(Vr^2 + Vi^2);
    Vlims = [ mpc.bus(:, VMIN) - Vm;
              Vm - mpc.bus(:, VMAX) ];

And, I'm sorry, it looks like I made some mistakes in the commented code I added to `opf_setup` (now corrected) that I'm sure added to the confusion. In each case, when you define the function handles that you will later pass to `om.add_nln_constraint`, the first arg is `x` for the `..._fcn` function and the first two args are `x` and `lam` for the `..._hess` function. Those arguments are updated by the solver at each iteration. The remaining arguments, which must be the same for the `..._fcn` and its corresponding `..._hess`, are there to provide any additional parameters you may need inside the function.

For the voltage magnitude constraints, you need `mpc` to get the values of `mpc.bus(:, VMIN)` and `mpc.bus(:, VMAX)`. For the voltage angle constraint for the reference buses, you need `mpc` and `refs` in order to get the value you are constraining the angles to, namely `mpc.bus(refs, VA)`. And for the branch angle limits, you'll need parameters `Aang`, `lang`, `uang`, and `iang` returned by `makeAang`. You'll see how they are used in 4.3 below.

Regarding `lam`, it is always a vector of shadow prices on the corresponding constraints. E.g. See `opf_branch_flow_hess` where it is the K-T multipliers on the "from" and "to" branch flow limits. So in `opf_vlim_hess` it should be the vector of multipliers on the lower and upper voltage magnitude constraints.

4.2 The voltage angle reference constraint will be something like:

    Varef = angle(Vr(refs) + 1j* Vi(refs)) - mpc.bus(refs, VA)

4.3 The branch angle difference constraints will be something like:

    Va = angle(Vr + 1j* Vi);
    Ax = Aang * Va;
    Va_diffs = [ lang - Ax;
                 Ax - uang ];

6. Ok, that makes sense. I'll try to decide and give you an answer soon.

Finally, just e-mail me if another Zoom call would help, in case some things are still unclear.

**Comment by BaljaaSS** [comment]
4.1 I have modified the voltage magnitude to voltage magnitude violations. I think it is correct now. 

4.2 and 4.3 I will do it on Friday.

**Comment by BaljaaSS** [comment]
I have created 4.1 and 4.3 as I understood. But there is still more left to do. Can you check it and give me comments?

7. The reason that we are doing 4.1, 4.2 and 4.3 is to improve the convergence of the version using Cartesian coordinates. Right? Do you think for my comparison of all four versions, should I include these constraints as well?  Thank you.

**Comment by rdzman** [comment]
I'll actually respond in reverse order ...

7. So, actually, no ... the purpose is not to improve convergence. The goal is to solve _the **same** OPF problem_ using different formulations. Without these constraints, it is actually a different problem that is being solved, which is why we are getting different solutions and the tests are failing. Voltage magnitudes must be constrained to lie between VMIN and VMAX, reference bus angles must be as specified, and branch angle differences must be constrained to the specified amounts, otherwise we are missing constraints that are in the original OPF formulation implemented in polar coordinates.

4.1, 4.2, 4.3  I looked at the new functions very briefly (didn't check all the derivatives, for example) and the only thing I noticed is that in `opf_vref_fcn` in line 40 the units for the angles should be consistently in radians, which means `mpc.bus(refs, VA)` should be `mpc.bus(refs, VA) * pi/180`.

The real way to check that the code is correct is to uncomment the code in `opf_setup` that adds these new constraints to the OPF and see if the tests in `t_opf_mips` begin to pass.

6. I've decided to leave TN2 largely unchanged and add two new ones, TN3 and TN4, which we will co-author. TN3 would add the missing current balance formulas for polar coordinates and TN4 would be the cartesian coordinate version, containing the equivalent of the content of both TN2 and TN3. Tentatively, here's what I have in mind for titles. Let me know what you think:

    - B. Sereeter and R. D. Zimmerman, _Addendum to AC Power Flows and their Derivatives using Complex Matrix Notation: Nodal Current Balance_, MATPOWER Technical Note 3, March 2018.
    - B. Sereeter and R. D. Zimmerman, _AC Power Flows and their Derivatives using Complex Matrix Notation and Cartesian Coordinate Voltages_, MATPOWER Technical Note 4, March 2018.

    I'm currently working on getting the basic structure of the documents set up and finalizing the notation. I'm trying to use notation that is very close to TN2 for consistency. I may ask for your help in the process depending how quickly it goes. If so, I'll give you access to the source in a private git repository on Bitbucket.

Thanks again for these contributions. I'm looking forward to seeing all the tests passing for all four variants.

**Comment by BaljaaSS** [comment]
I am in holiday for the rest of the week. I will be back in next week.

4.1, 4.2 and 4.3 I will finalize them next week including the description text.
6.  The title is okay for me. If you need my help, I can help on writing TN3 and TN4. 
7.  I see now.

**Comment by rdzman** [comment]
Ok, I did a force push with a cleaned up set of commits. I then merged it with another local branch on the main MATPOWER repo and didn't realize that it would mark it as merged. I'll continue working on the opt-variants branch in the main repo for now.

**Comment by rdzman** [comment]
Now merged into master.

**Pull request merged**
