### PR TITLE
Variants of the Newton power flow

### PR DESCRIPTION
**Pull request by BaljaaSS**
This branch includes different variants of the Newton power flow (NR) method using different mismatch formulations and coordinates for the power flow computation. 

- newtonpf() includes all four variants of NR. Depending on the choice of **mpopt.pf.current_balance** and **mpopt.pf.v_cartesian**, it uses the power or current balance equations in polar and Cartesian coordinates. newtonpf() can be improved for some parts. 

- Each variant is also implemented and named as **newtonpf_PP** (original newtonpf using power balance in polar coordinates), **newtonpf_PC** (NR using power balance in Cartesian coordinates), **newtonpf_CP** (NR using current balance in polar coordinates) and **newtonpf_CC** (NR using current balance in Cartesian coordinates).

### CODE REVIEW

**Comment by rdzman** [comment]
Thanks. Here are a few comments/requests, in no particular order.

- Could you do me a favor, and explicitly describe the elements of _x_ and _g_(_x_) for each of the variants, as in (4.4) and (4.5) in the [MATPOWER 6.0 User's Manual](
http://www.pserc.cornell.edu/matpower/docs/MATPOWER-manual-6.0.pdf)? That would help me understand more quickly the precise formulation for each variant.

- For consistency with the OPF variants, let's always put `Vr` before `Vi` (e.g. in _x_).

- Since the variants really only apply to the `'NR'` power flow, I think it might be better to simply add 3 more options to the `pf.algs` options, e.g. `'NR-Ip'`, `'NR-Sc'`, `'NR-Ic'` (and `'NR-Sp'` as a synonym for `'NR'`). Otherwise, we have to check and throw an error if `pf.v_cartesian` or `pf.current_balance` are set when `pf.algs` is equal to something other than `'NR'`. What do you think?

- Add tests in `t_pf`. I would add one for each variant at the beginning, then put everything following the DC PF test into loop that tests all 4 variants.

- Add tests in `t_vdep_load` to test each of the 4 variants for the NR power flow case. Some quick testing I did suggests your implementation of the variants may not be working for voltage dependent loads.

**Comment by rdzman** [comment]
Sorry, ignore my first bullet point. I just realized you had already sent me those details and more in a report via e-mail.

**Comment by BaljaaSS** [comment]
For the second bullet, can refer to the specific location? 

As you can see I have changed the name of Netwonpf functions and added options to _pf.algs_ in **mpoption** as well as **runpf**. However, there is still no relation between the choice of _pf.algs_ and _pf.current_balance_ or _pf.v_cartesian_.  I think we should add options that depending on values of _pf.current_balance_ or _pf.v_cartesian_ the value of _pf.algs_ is changed automatically. However, can we do it in _mpoption.m_ ?

For fourth and fifth bullet points, now I understood. I will do it next week.

**Comment by rdzman** [comment]
For the second bullet, I was referring to the ordering of the _x_ vector and the columns of the Jacobian in `newtonpf_S_cart()` and `newtonpf_I_cart()`. In the OPF, the elements of _x_ are ordered with real part of _V_ followed by the imaginary part of _V_, then _P_, then _Q_. I'd like to keep the ordering of the relevant elements of _x_ consistent for the power flow.

My idea was to eliminate `pf.v_cartesian` and `pf.current_balance` completely and just use `pf.algs`.

**Comment by BaljaaSS** [comment]
**pf.v_cartesian** and **pf.current_balance** are eliminated from mpoption.m. 

I have changed the order of Vi and Vr in X and solved the test cases to make sure. As I expected, modified **newtonpf_S_cart** works fine for small cases and converges really slow for large cases and does not work for case13659pegase (error at dx = mplinsolve(J, -F, lin_solver);). I think because of the following reasons, it happens:

1. In modified **newtonpf_S_cart**, we will have following submatrices for     
 J = [   j11 j12;
            j21 j22;    ]
where
    j11 = real(dSbus_dVr([pv; pq], pq));
    j12 = real(dSbus_dVi([pv; pq], [pv; pq]));
    j21 = imag(dSbus_dVr(pq, pq));    
    j22 = imag(dSbus_dVi(pq, [pv; pq]));
which results  [**pv pq pq**] x [**pq pv pq**] whereas before it was [**pv pq pq**] x [**pv pq pq**] which was same as newtonpf. Maybe this gives different properties for the Jacobian matrix for the large cases that results in different performance. 

2. When I developed these versions, I was thinking as Va<=>Vi and Vm<=>Vr. Therefore, I used the equation (14) in the report I sent to you in order to make the Jacobian square matrix. So I added dP/dVr and dQ/dVr into dP/dVi and dQ/dVi respectively using equation (14). As a result, we don't have derivatives w.r.t dVr for pv buses in the Jacobian as derivatives w.r.t Vm are removed from Jacobian for pv buses in **newtonpf**.  Therefore, the structure remains the same.  Now, when I change the order of Vr and Vi while using equation (14), it results in different performance.

**Solution**

1.  We can use equation (14) other-way around which means we compute dVi in terms of dVr from equation (14) then update the Jacobian. However, it requires more work and we don't know if it performs better or worse than what we have now.

2. We keep Vi and Vr order and change the order of these two in the OPF. 

Personally, I prefer 2nd because 1st is more work for changing order.  What do you think?  

Meanwhile, I will work on tests.

**Comment by abhyshr** [comment]
Don’t know if this helps….We had written a paper comparing the conventional power balance (PB) - polar coordinate power flow solution with a hybrid current-power balance (HPCB) – rectangular coordinate solution. Our observation, based on testing of several MATPOWER cases, was that the HPCB approach was faster than PB. The largest test case we tried, which was the largest in MATPOWER at that time, was case3120sp.

Shri

Note: The code for PB and HPCB was written in C. Section IV has the implementation details.

**Comment by BaljaaSS** [comment]
As you suggested, when I make Jacobian [pq pv pq] x [pq pv pq], it worked. In this case, we have exactly the same blocks in different positions. Thank you and Shri for your comment. Now they perform the same and we have [Vr Vi] order in x. I don't  know exactly the problem for Jacobian having [pv pq pq] x [pq pv pq]. I guess it was the same set of equations but not the same blocks as before. 

I have added tests for variants of NR in t_pf as you suggested. Errors you have seen before, are solved. Now there is a new error which I don't know how to fix. Maybe you can give me a hint. My guess is where I finish my **end** for the **loop**.

Meanwhile, I will work on **t_vdep_load**

**Comment by BaljaaSS** [comment]
3. In [863a4d8 ](https://github.com/MATPOWER/matpower/pull/43/commits/863a4d85b43dc8e4c9a36fc9cd4df29f0a4e887f), you can see the theory for the derivatives of the power and current balance equations having voltage dependent loads. I think it is correct but you can double check. It can be included in one of the Technical Note. 

4. In [e826dce](https://github.com/MATPOWER/matpower/pull/43/commits/e826dce43ed27ccf7df52ef7f25ad2f1a8f704c9), you can see how makeSbus() will look like. You can give comments on how I should implement it and name it. Without knowing these, it is not easy to implement since changes require adaptations of other functions.

**Comment by rdzman** [comment]
I just rebased this branch on top of the current `master` and did a force push, so please be sure to update your local branch before continuing work on this branch:
```
git fetch --all
git reset --hard origin/variants-NR
```

**Comment by rdzman** [comment]
First, sorry for such a delay on this.

So, I cleaned up and reorganized `t_pf` on the `master` branch in a way that made it trivial to get the tests passing for your new Newton formulations. To get the tests to pass, I had to revert `makeSbus.m` to the original, but I put your modified version in `makeSbus-bali.m` temporarily.

I just re-based this PF again on the latest `master`, then did another force push. So once again please be sure to update your local branch before continuing work on this branch:

```
git fetch --all
git reset --hard origin/variants-NR
```

**Comment by rdzman** [comment]
Second, given the facts that (1) we didn't include support for voltage dependent loads in the 3 new variants of the OPF formulation, and (2) the voltage dependent load feature is experimental and really needs to be fully revamped to allow independently setting the characteristics of each individual load, I am now thinking that support for voltage dependent loads for these variants is not critical. It would still be nice if you have the time, but it's not critical. We'd just need to make sure that it throws errors if you try to use a combination that isn't implemented.

And, responding to your points above ...

1. See 4.

2. Upon further reflection, I think the choice of cartesian vs. polar and power vs current mismatch, is properly a modeling choice, not an algorithm choice, so let's go back to using `pf.v_cartesian` and `pf.current_balance`, also for consistency with the OPF. We will need to throw an error if the `pf.alg` option is set to anything but `'NR'`. I may even decide to merge the `pf.v_cartesian` and `opf.v_cartesian` into a single option that applies to both and similarly for `current_balance`. What do you think? I haven't decided yet.

3. I checked the formulas for the voltage dependent loads in `Derivatives.pdf` and everything looks fine. But, we’re going to need the 2nd derivatives if we want to include these for the OPF, right?

4. If we go ahead with support for voltage dependent loads now, I think I would prefer that we pull out the computation of the derivatives of the loads into a new `dSd_dV.m`, with interface as follows, where `Sd` is the struct returned by `makeSdzip()`:
    ```
    [dSd_dV1, dSd_dV2] = dSd_dV(Sd, V, vcart);
    % for example ...
             [dSd_dVm] = dSd_dV(Sd, Vm)     % one output AND vcart empty or 0
             [dSd_dVm] = dSd_dV(Sd, Vm, 0)  %    => 2nd input is Vm, not V
    [dSd_dVa, dSd_dVm] = dSd_dV(Sd, V,  0)
    [dSd_dVr, dSd_dVi] = dSd_dV(Sd, V,  1)
    ```
    We may also need `dId_dV.m` and possibly even `dIg_dV.m`, right?

**Comment by BaljaaSS** [comment]
Thank you for your comments. 

(1.) (3.) (4.)  I agree that the support for voltage-dependent loads for these variants is not critical since it is just different formulas for loads and it does not influence the algorithm. In addition, I also do not have time to work on that as I have to finish my Ph.D. in 6 months. Maybe it is really needed I can work on that after my Ph.D. You are right that we need 2nd derivatives of voltage-dependent loads in OPF computations.  I think `dId_dV.m` and `dIg_dV.m` can be in one function. 

(2.) We still use the same Newton-Raphson algorithm to solve the nonlinear system of equations having different values due to different balance equations and coordinates. As you said it a modeling choice. I can add `pf.v_cartesian` and `pf.current_balance`. if you merge `pf.v_cartesian` and `opf.v_cartesian` then you will save some options but I think it is still possible for PF to have different model than mine but the same formulations and coordinates. In that case, `pf.v_cartesian` and `pf.current_balance` are still not enough for PF. I would keep both `pf.v_cartesian` and `opf.v_cartesian`. 

(5) I will add `pf.v_cartesian` and `pf.current_balance` options in `mpoption.m`. NR variants will use  the constant load model. I think it should work now ?

**Comment by rdzman** [comment]
Eventually, it would be nice to have everything combined in one `newtonpf.m` and use function handles to deal cleanly with the parts that are different between the variations, analogous to the way the OPF works now. But this can wait for later as well. I prefer the separate functions as it is now over a `newtonpf.m` fill of `if` statements to deal with the variations.

What do you think of the following idea? We add back the `pf.v_cartesian` and `pf.current_balance` options and use them for all logic internally, but we also leave the alternate `pf.alg` options (`NR-SC`, `NR-IP`, `NR-IC`) as shortcuts for automatically setting (overriding) both options at once. That is, somewhere in `runpf` before dispatching to the various AC power flow routines, we check if the `alg` is one of these three, and if so, we set the `pf.v_cartesian` and `pf.current_balance` options accordingly. If you're ok with this idea, let's go with it.

Finally, we'll need to add some documentation to the manual about these formulations. Has that report "On a comparison of Newton-Raphson solvers for power flow problems" that you sent me previously been published somewhere? It's a good reference.

**Comment by BaljaaSS** [comment]
I am okay with the idea. I think it is the easiest way to hand it for now. 

I have added `pf.v_cartesian` and `pf.current_balance` options in `mpoption.m` and made it possible to change their values using the choice of `alg` in `runpf.m` as you said. Now, 't_pf' passes all tests.   

About the report, I have submitted it in "Journal of Computational Applied Mathematics" and I am still waiting for the decision. We can use the published version as a reference. I will provide the citation.  

Is there anything that we have to check or do for this pull-request on variants of NR?

**Comment by rdzman** [comment]
I think this is ready. Could you have a final look at this before I merge it?

My latest changes are:
- Rebase again on the latest `master` branch.
- Minor modifications to your last commit (now ad2b719). Now the dispatching in `runpf` is based purely on the values of `pf.current_balance` and `pf.v_cartesian`.
- Add help text to `newtonpf*` functions.
- Add error message if attempting to use one of the new variants with a non-Newton power flow algorithm.
- Update the documentation. Could you please have a look at my additions to the manual to make sure everything is correct? And, please update the citation to your paper as needed.

Thanks again, Bali! This is nice work that I'm very happy to be able to include. :clap:
I'll plan to merge it as soon as I have your OK.

**Comment by BaljaaSS** [comment]
Hi Ray,

I checked all your changes. It seems everything is OK.  I also read .tex of the manual and the only thing I would add is that the explanation of handling PV buses in subsubsection "Cartesian vs. Polar Coordinates for Voltage" whereas it is mentioned in subsubsection "Current vs. Power for Nodal Balance Equations". 

I will update the citation when the paper is accepted. Thank you for including these variants of NR in Matpower. I am happy that people can use these variants through Matpower.

When I have more time (after my PhD), I would like to contribute more to Matpower as I have 3 phase implementations of these variants of NR (Ybus, Sbus in 3 phase as well), voltage-dependent loads on these variants of NR, Linear power flow computation using constant impedance model if you like.

**Comment by rdzman** [comment]
Thanks.

I'm not sure I understand what you are suggesting for the paragraph on handling PV buses in the manual. I went back to the code to double-check, and that explanation does only apply to the current based versions, correct?

I certainly welcome your continued contributions. For one, I'd be interested in your feedback on #40, in particular on any improved methods for handling PV buses in the implicit Zbus Gauss method. I am also about to begin work on three-phase unbalanced modeling for MATPOWER. Maybe we could arrange a conversation about what you've already done.

**Comment by BaljaaSS** [comment]
Correct. Moreover, we need to use one of the equations (2) and (3) as you can find in the report to handle PV buses in power cartesian variant. But it is also okay to write like that.

I will check #40 and let you know my feedback on that. We can arrange a conversation on three-phase modeling through Skype. I am also attending SIAM CSE19 and IEEE PES GM 19 conferences in the USA. If you are attending one of these conferences we can also meet there as well.

**Comment by rdzman** [comment]
Ok, how about this in the section on Cartesian vs. Polar?

For PV buses, since the voltage magnitude is constant, $\Delta u$ can be expressed as a function of $\Delta w$, allowing $u$ to be eliminated for PV buses by modifying the Jacobian terms corresponding to $g_P$ and $w$. This results once again in a system of nonlinear equations with $n_{pv} + 2n_{pq}$ equations and unknowns.

**Comment by rdzman** [comment]
In looking more closely at these details in the code, I ended up with a question. For the cartesian versions, why are the voltage updates implemented (especially for PQ buses) using equations (2) and (3) from the report, as opposed to updating the real and imaginary parts of V directly?

That is, why do we do this ...
```
    if npv
        Va(pv) = Va(pv) + dx(j3:j4) ./ real(V(pv));
    end
    if npq
        Vm(pq) = Vm(pq) + (real(V(pq))./Vm(pq)) .* dx(j1:j2) ...
                        + (imag(V(pq))./Vm(pq)) .* dx(j5:j6);
        Va(pq) = Va(pq) + (real(V(pq))./(Vm(pq).^2)) .* dx(j5:j6) ...
                        - (imag(V(pq))./(Vm(pq).^2)) .* dx(j1:j2);
    end
    V = Vm .* exp(1j * Va);
```
... rather than this?
```
    if npv
        Va(pv) = Va(pv) + dx(j3:j4) ./ real(V(pv));
        V(pv) = Vm(pv) .* exp(1j * Va(pv);
    end
    if npq
        V = V + dx(j1:j2) + 1j * dx(j5:j6);
    end
```

It seems that for the PV buses we could even do this ...
```
    if npv
        U = real(V(pv));
        W = imag(V(pv));
        dW = dx(j3:j4);
        dU = -U + sqrt(U.^2 - (2 * W + dW) .* dW);
        V(pv) = V(pv) + dU + 1j * dW;
    end
    if npq
        V = V + dx(j1:j2) + 1j * dx(j5:j6);
    end
```
... where the formula for `dU` comes from expressing the invariance of `Vm` as ...
```
U^2 + V^2 = (U+dU)^2 + (W+dW)^2
```
... and solving it for `dU` (assuming I did it correctly).

I don't think these approaches are strictly equivalent, though I expect they should all work, right?

I'm interested in hearing your thoughts, and why you chose the option you did.

**Comment by rdzman** [comment]
In fact, I did just confirm that all 3 alternatives work, but do not produce exactly the same iterates.

**Comment by BaljaaSS** [comment]
For the explanation in the manual, that is fine. 

I have compared all the approaches for updating `V`. For updating the real and imaginary parts of `V` directly, it works fine on only small cases. We can use this approach if there are no PV buses. On large cases, this approach was not as good as my current implementation on Matpower. I think the main reason is that Jacobian is altered using equations (2) and (3). Let's say Jacobian depends on equations (2) and (3). Then when you update voltage corrections you should also use these equations. Equations (2) and (3) give the relation between corrections in polar and in Cartesian coordinates. Therefore, using these two equations to update voltage magnitude and angles gives us the robust and fastest convergences. It is like pre-smoothing and post-smoothing in Multigrid. Does it help?

**Comment by rdzman** [comment]
Thanks! I'm going to clean up the commit history a bit for this PR and then merge. I also caught a bug where the new variants were only being used if `mpopt.verbose` was > 0.

Thanks again for this nice contribution!

**Pull request merged**
