### PR TITLE
use explicit LU of Jacobian to speed up Newton step

### PR DESCRIPTION
**Pull request by rdzman**
Based on [this post](http://www.mail-archive.com/matpower-l@cornell.edu/msg05499.html), I [added some additional options](https://github.com/MATPOWER/mips/commit/155b3582b8cab974ca6f929012833b5b3dd9fc4e) to [`mplinsolve()`](https://github.com/MATPOWER/mips/blob/lu/lib/mplinsolve.m), then modified `newtonpf` to call `mplinsolve` instead of using `x = -(J \ F)`.

This results in a significant speedup in Matlab. I am using the Gilbert-Peierls algorithm, although it appears that the vast majority of the speedup is due to the AMD ordering. The speedup of `runpf` is on the order of 1.3x - 2.0x for cases with 300 or more buses.

In Octave, on the other hand, simply using an explicit LU with back-substitution, without the AMD reordering or supplying the pivot threshold of 1.0, appears to be the fastest on most cases, with the maximum speedups on the order of only 1.1x. For systems smaller than 1000 buses, even this appears to provide no advantage, so we stick with `/` for those cases.

### CODE REVIEW

**Comment by rdzman** [comment]
Here is some code I used for benchmarking (based off of [this code](http://www.mail-archive.com/matpower-l@cornell.edu/msg05501.html) from Jose Marin):

```matlab
case_list = {
    'case4gs', 'case5', 'case6ww', 'case9', 'case14', 'case18', 'case22', ...
    'case24_ieee_rts', 'case30', 'case33bw', 'case39', 'case57', ...
    'case69', 'case85', 'case89pegase', 'case118', 'case141', ...
    'case145', 'case300', 'case1354pegase', 'case1888rte', 'case1951rte', ...
    'case2383wp', 'case2736sp', 'case2737sop', 'case2746wop', ...
    'case2746wp', 'case2848rte', 'case2868rte', 'case2869pegase', ...
    'case3012wp', 'case3120sp', 'case3375wp', ...
    'case6468rte', 'case6470rte', 'case6495rte', 'case6515rte', ...
    'case9241pegase', 'case13659pegase' };
solvers = {'\', 'LU', 'LU_AMD', 'LU_GP', ''};
NREPEAT = 15;

m = length(case_list);
n = length(solvers);
mpopt = mpoption('pf.alg', 'NR', 'pf.tol', 1.0e-10, 'pf.nr.max_it', 100, 'out.all', 0, 'verbose', 0);

timings = zeros(NREPEAT,1);
tt = zeros(m, n);
for s = 1:n
    mpopt = mpoption(mpopt, 'pf.nr.lin_solver', solvers{s});
    fprintf('\n%-7s ', solvers{s});
    for k = 1:m
        cfile = char(case_list(k));
        mpc = loadcase(cfile);
        for i = 1:NREPEAT;
            r = runpf(mpc, mpopt);
            timings(i) = r.et;
        end
        timings = sort(timings);
        tt(k, s) = mean(timings(1:ceil(NREPEAT/3)));
        fprintf('.');
    end
end
speedups = (tt(:, 1) * [1 1 1 1]) ./ tt(:, 2:5);
total_speedups = sum(tt(:, 1) * [1 1 1 1]) ./ sum(tt(:, 2:5));

fprintf('\n');
fprintf('\nSpeed-up relative to using default built-in \\ operator.\n');
fprintf('                       LU    LU_AMD   LU_GP  default\n');
fprintf('                      -----  ------   -----  -------\n');
for k = 1:m
    fprintf('%-20s: %.3f   %.3f   %.3f   %.3f\n', case_list{k}, speedups(k, :));
end
fprintf('\n%19s : %.3f   %.3f   %.3f   %.3f\n', 'total', total_speedups);
fprintf('%19s : %.3f   %.3f   %.3f   %.3f\n', 'min', min(speedups));
fprintf('%19s : %.3f   %.3f   %.3f   %.3f\n', 'mean', mean(speedups));
fprintf('%19s : %.3f   %.3f   %.3f   %.3f\n', 'median', median(speedups));
fprintf('%19s : %.3f   %.3f   %.3f   %.3f\n', 'max', max(speedups));
```

**Comment by rdzman** [comment]
And here's the output from a run on my laptop:

```text
\       .......................................
LU      .......................................
LU_AMD  .......................................
LU_GP   .......................................
        .......................................

Speed-up relative to using default built-in \ operator.
                       LU    LU_AMD   LU_GP  default
                      -----  ------   -----  -------
case4gs             : 1.025   1.348   1.503   1.401
case5               : 0.999   1.447   1.688   1.694
case6ww             : 1.062   1.331   1.369   1.328
case9               : 1.177   1.340   1.333   1.323
case14              : 1.044   1.620   1.606   1.427
case18              : 1.008   1.399   1.396   1.315
case22              : 0.986   1.181   1.202   1.074
case24_ieee_rts     : 1.016   1.217   1.229   1.120
case30              : 0.877   1.180   1.188   1.173
case33bw            : 0.981   1.154   1.169   1.106
case39              : 1.166   1.364   1.362   1.338
case57              : 1.018   1.271   1.249   1.250
case69              : 0.919   1.229   1.144   1.167
case85              : 1.000   1.222   1.099   1.223
case89pegase        : 0.994   1.345   1.351   1.333
case118             : 0.998   1.346   1.340   1.315
case141             : 0.986   1.275   1.271   1.259
case145             : 1.003   1.241   1.232   1.222
case300             : 1.005   1.389   1.380   1.381
case1354pegase      : 1.013   1.567   1.566   1.579
case1888rte         : 1.035   1.380   1.356   1.366
case1951rte         : 0.935   1.447   1.425   1.435
case2383wp          : 1.015   1.664   1.613   1.660
case2736sp          : 0.979   1.617   1.540   1.653
case2737sop         : 1.006   1.690   1.721   1.697
case2746wop         : 0.995   1.714   1.704   1.735
case2746wp          : 1.002   1.657   1.604   1.653
case2848rte         : 0.915   1.442   1.475   1.352
case2868rte         : 1.015   1.653   1.662   1.645
case2869pegase      : 1.068   1.799   1.819   1.815
case3012wp          : 1.009   1.606   1.671   1.679
case3120sp          : 1.020   1.679   1.689   1.685
case3375wp          : 0.965   1.581   1.590   1.592
case6468rte         : 0.949   1.585   1.625   1.581
case6470rte         : 1.014   1.796   1.799   1.761
case6495rte         : 0.993   1.642   1.635   1.619
case6515rte         : 0.982   1.752   1.719   1.706
case9241pegase      : 1.036   1.980   1.962   1.974
case13659pegase     : 1.030   1.965   1.974   1.941

              total : 1.016   1.792   1.789   1.784
                min : 0.877   1.154   1.099   1.074
               mean : 1.006   1.490   1.494   1.476
             median : 1.005   1.447   1.503   1.427
                max : 1.177   1.980   1.974   1.974
```

**Comment by jl-marin** [comment]
Two quick comments:

- I believe that what makes MATLAB use GP instead of the default UMFPACK is not the presence of the threshold parameter, but the use of the *three-output syntax* (two-output syntax would do that too, according to the FACTORIZE paper). I'm saying this because of your comments in that part of the code.

-  In your numerical results, I find it odd that the column labeled "default" shows a speedup w.r.t. the backslash operator.  Wouldn't the speedup have to be very near 1?

**Comment by rdzman** [comment]
Thanks for the link to the Davis [FACTORIZE paper](http://dl.acm.org/citation.cfm?id=2491498) in your [MATPOWER-DEV-L post](http://www.mail-archive.com/matpower-dev-l@cornell.edu/msg00006.html).

So, I think I'll revise the `pf.nr.lin_solver` options and the comments in `mplinsolve()` to make the UMFPACK vs. GP clear and consistent.

Regarding the "default" column in the benchmarking output, that refers to the default solver used when the `pf.nr.lin_solver` option is a blank string, which it is by default. In that case, it chooses `'LU_GP'` under Matlab and `'LU'` under Octave (attempting to choose the best option available), so when running under Matlab the results of the default column should be very similar to the previous column.

**Comment by rdzman** [comment]
I just pushed an update. I changed the values for selecting the solver to `LU`, `LU3`, `LU4`, etc. See the help text in `mplinsolve` for details.

Here is a [plot of the speedups](https://www.dropbox.com/s/ib7ydbxycjuf47l/speedup-matlab-10.pdf?dl=0) I'm seeing for `mplinsolve` (not for `runpf`). The dotted line goes with the right axis and shows the dimension of A. The one listed as `<default>` corresponds to the default selected automatically by `newtonpf` depending on the size.

**Comment by rdzman** [comment]
I'd like to merge this in to `master`. Any objections, @jl-marin ?

**Pull request merged**
